import assert from 'node:assert/strict';
export const metadata = { name: 'completed-process-height-and-compact-memory', profiles: ['desktop', 'mobile'] };
// Synthetic preview: --experience --display-regression. No production Turn is submitted.
export default async function ({ page, evidence, baseUrl, profile }) {
  page.setDefaultTimeout(15000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(baseUrl);
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await page.locator('.cwu-composer textarea').fill(`显示回归 ${profile} ${Date.now()}`);
  await page.locator('.cwu-composer button[type=submit]').click();
  const closeList = page.getByRole('button', { name: '收起列表', exact: true });
  if (profile === 'mobile' && await closeList.isVisible()) await closeList.click();
  const process = page.locator('.cwu-technical.is-progressive');
  await process.locator('.cwu-technical-toggle').click();
  await process.locator('.cwu-process-copy').getByText('进度 45：正在核对完成后的记录高度和记忆来源。', { exact: false }).waitFor();
  const running = await process.evaluate(el => {
    const list = el.querySelector('.cwu-progressive-list');
    return { running: el.classList.contains('is-running'), height: list.clientHeight, scroll: !!list.querySelector(':scope > .cwu-scroll-content'), max: getComputedStyle(list).maxHeight };
  });
  assert.equal(running.running, true);
  assert.equal(running.scroll, false, 'running execution records are not capped');
  assert.equal(running.max, 'none');
  assert.ok(running.height > 600);
  await evidence.checkpoint('正在执行时长进度完整展示，不限高');
  await page.locator('.cwu-memory-sources summary').waitFor();
  await page.waitForFunction(() => document.querySelector('.cwu-progressive-list')?.dataset.overflow === 'true');
  const completed = await process.evaluate(el => {
    const list = el.querySelector('.cwu-progressive-list'), content = list.querySelector(':scope > .cwu-scroll-content');
    return { running: el.classList.contains('is-running'), height: content.clientHeight, scrollHeight: content.scrollHeight, limit: Math.min(400, innerHeight * .48), overflow: getComputedStyle(content).overflowY };
  });
  assert.equal(completed.running, false);
  assert.ok(completed.height <= completed.limit + 1);
  assert.ok(completed.scrollHeight > completed.height + 200);
  assert.equal(completed.overflow, 'auto');
  await evidence.checkpoint('完成后同一条记录自动限高并提供内部滚动');
  const scroll = process.locator('.cwu-progressive-list > .cwu-scroll-content');
  await scroll.evaluate(el => { el.scrollTop = el.scrollHeight; });
  await page.waitForFunction(() => document.querySelector('.cwu-progressive-list > .cwu-scroll-content')?.scrollTop > 0);
  const command = process.locator('button.cwu-process-summary').filter({ hasText: 'node inspect.js' });
  await command.click();
  assert.ok((await scroll.evaluate(el => el.clientHeight)) <= completed.limit + 1, 'expanding a long command retains the outer cap');
  await evidence.checkpoint('可滚到底，展开命令输出仍保持外层高度上限');
  await process.locator('.cwu-technical-toggle').click();
  await process.locator('.cwu-technical-toggle').click();
  await page.waitForFunction(() => document.querySelector('.cwu-progressive-list')?.dataset.overflow === 'true');
  const memory = page.locator('.cwu-memory-sources');
  assert.equal(await memory.getAttribute('open'), null);
  assert.match(await memory.locator('summary').innerText(), /参考记忆\s*· 5/);
  assert.equal(await memory.getByRole('button', { name: 'Core.md', exact: true }).isVisible(), false);
  const trigger = memory.locator('summary');
  const triggerBox = await trigger.boundingBox();
  assert.ok(triggerBox.width < 180, 'five long filenames remain a compact collapsed entry');
  await evidence.checkpoint('五份记忆默认收为一个轻量入口');
  await evidence.action('展开参考记忆', trigger, el => el.click());
  assert.equal(await memory.getByRole('button').count(), 5);
  await memory.getByRole('button', { name: 'Communication-and-Expression.md', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await evidence.checkpoint('完整来源按行显示，手机长文件名无横向溢出');
  await evidence.action('来源仍可站内预览', memory.getByRole('button', { name: 'Core.md', exact: true }), el => el.click());
  await page.locator('.cwu-document-content').getByText('合成验收记忆：回复使用中文，文件在站内预览。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '关闭文件预览', exact: true }).click();
  await page.locator('.cwu-document-backdrop').waitFor({ state: 'detached' });
  await memory.locator('summary').click();
  const toggleWidth = await process.locator('.cwu-technical-toggle').evaluate(el => el.getBoundingClientRect().width);
  assert.ok(toggleWidth < 160, 'execution disclosure no longer fills the reply width');
  assert.deepEqual(errors, []);
  await evidence.checkpoint('关闭预览回到原位，两个入口都保持紧凑');
}
