import assert from 'node:assert/strict';
export const metadata = { name: 'related-sessions-and-realtime', profiles: ['desktop', 'mobile'] };
export default async function ({ page, evidence, baseUrl }) {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  // This exercises denial without opening the physical microphone or a model Turn.
  await page.addInitScript(() => { navigator.mediaDevices.getUserMedia = async () => { throw new DOMException('验收：麦克风授权被拒绝', 'NotAllowedError'); }; });
  await page.goto(baseUrl);
  await page.locator('.cwu-composer textarea').waitFor();
  await page.getByLabel('会话更多操作', { exact: true }).click();
  const menu = page.locator('.cwu-product-session-tools');
  for (const name of ['Side Chat', 'Subagent', '线程关系']) assert.equal(await menu.getByRole('button', { name, exact: true }).count(), 0);
  await menu.getByRole('button', { name: '关联会话', exact: true }).click();
  const related = page.getByRole('dialog', { name: '关联会话', exact: true });
  const relatedTabs = related.getByRole('tablist', { name: '关联会话', exact: true });
  assert.equal(await relatedTabs.getByRole('tab').count(), 3);
  assert.equal(await related.getByRole('tablist').count(), 1);
  await related.locator('textarea').waitFor();
  await related.locator('textarea').fill('尚未发送的 Side Chat 草稿');
  await evidence.checkpoint('Side Chat 与关联会话统一入口');
  await relatedTabs.getByRole('tab', { name: 'Subagent', exact: true }).click();
  await related.getByRole('tabpanel').waitFor();
  await evidence.checkpoint('同一弹窗切换 Subagent');
  await relatedTabs.getByRole('tab', { name: '线程关系', exact: true }).click();
  await related.getByRole('button', { name: '刷新关系', exact: true }).waitFor({ timeout: 30000 });
  assert.ok(await related.locator('.cwu-thread-relations li').count() >= 1);
  assert.equal(await related.locator('pre').count(), 0);
  await evidence.checkpoint('线程关系自动读取与可读列表');
  await relatedTabs.getByRole('tab', { name: '线程关系', exact: true }).press('Home');
  assert.equal(await relatedTabs.getByRole('tab', { name: 'Side Chat', exact: true }).getAttribute('aria-selected'), 'true');
  assert.equal(await related.locator('textarea').inputValue(), '尚未发送的 Side Chat 草稿');
  await related.getByRole('button', { name: '关闭会话工具', exact: true }).click();
  await page.getByLabel('会话更多操作', { exact: true }).click();
  await page.getByRole('button', { name: '实时语音', exact: true }).click();
  const realtime = page.getByRole('dialog', { name: '实时语音', exact: true });
  await realtime.getByRole('combobox', { name: '声音', exact: true }).locator('option').nth(8).waitFor({ state: 'attached' });
  assert.equal(await page.locator('dialog[open]').count(), 1);
  assert.equal(await realtime.getByRole('button', { name: '语音', exact: true }).count(), 0);
  assert.equal(await realtime.getByRole('button', { name: '开始实时对话', exact: true }).isEnabled(), true);
  await evidence.checkpoint('实时语音直接显示控制与真实声音列表');
  await realtime.getByRole('button', { name: '开始实时对话', exact: true }).click();
  await realtime.getByText('验收：麦克风授权被拒绝', { exact: true }).waitFor();
  assert.equal(await realtime.getByRole('button', { name: '开始实时对话', exact: true }).isEnabled(), true);
  await evidence.checkpoint('授权失败提示可见且页面保持可用');
  await realtime.getByRole('button', { name: '改用文字输入', exact: true }).click();
  await realtime.waitFor({ state: 'hidden' });
  await page.getByLabel('会话更多操作', { exact: true }).click();
  await page.getByRole('button', { name: '实时语音', exact: true }).click();
  await realtime.getByRole('button', { name: '开始实时对话', exact: true }).waitFor();
  await realtime.getByRole('button', { name: '关闭会话工具', exact: true }).click();
  await page.locator('.cwu-composer textarea').waitFor();
  assert.deepEqual(errors, []);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
}
