import assert from 'node:assert/strict';
export const metadata = { name: 'unified-turn-detail-tabs', profiles: ['desktop', 'mobile'] };
// Synthetic preview: --experience --display-regression. No production Turn is submitted.
export default async function ({ page, evidence, baseUrl, profile }) {
  page.setDefaultTimeout(15000);
  const errors = [], processReads = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (new URL(request.url()).pathname.includes('/process/')) processReads.push(request.url()); });
  await page.goto(baseUrl);
  await page.getByRole('button', { name: '新建对话', exact: true }).click();
  await page.locator('.cwu-composer textarea').fill(`显示回归 ${profile} ${Date.now()}`);
  await page.locator('.cwu-composer button[type=submit]').click();
  const closeList = page.getByRole('button', { name: '收起列表', exact: true });
  if (profile === 'mobile' && await closeList.isVisible()) await closeList.click();
  const card = page.locator('.cwu-technical.is-tabbed');
  await card.waitFor();
  assert.equal(await card.getAttribute('data-open'), 'true', 'running turn detail card defaults to open');
  assert.equal(await page.locator('.cwu-technical-toggle, .cwu-memory-sources').count(), 0);
  await evidence.checkpoint('运行中默认展开，无双开关和旧记忆入口');
  await card.getByRole('tab', { name: /^执行记录/ }).click();
  assert.equal(await card.getAttribute('data-open'), 'false', 'clicking the selected tab collapses the card');
  await card.locator('.cwu-turn-detail-header').click({ position: { x: 2, y: 24 } });
  assert.equal(await card.getAttribute('data-open'), 'true', 'clicking the card header outside buttons reopens');
  await card.locator('.cwu-process-copy').getByText('进度 45：正在核对完成后的记录高度和记忆来源。', { exact: false }).waitFor();
  const running = await card.evaluate(el => {
    const list = el.querySelector('.cwu-progressive-list');
    return { running: el.classList.contains('is-running'), height: list.clientHeight, scroll: !!list.querySelector(':scope > .cwu-scroll-content'), max: getComputedStyle(list).maxHeight };
  });
  assert.equal(running.running, true); assert.equal(running.scroll, false); assert.equal(running.max, 'none'); assert.ok(running.height > 600);
  assert.equal(await card.locator('.type-assistant .cwu-process-summary').count(), 0, 'plain progress has no separate provider heading');
  await evidence.checkpoint('打开运行记录不限高，普通进度不重复拆成标题和正文');
  await card.getByRole('tab', { name: /^参考记忆/ }).click();
  await card.getByRole('tab', { name: /^参考记忆\s*5$/ }).waitFor();
  assert.equal(await card.getByRole('tab', { name: /^参考记忆/ }).getAttribute('aria-selected'), 'true', 'completion metadata retains selected tab');
  assert.equal(await card.locator('.cwu-memory-source-list button').count(), 5);
  assert.equal(await card.locator('.cwu-progressive-list').count(), 0);
  await evidence.checkpoint('参考记忆展示五份真实来源，完成刷新仍停留在当前Tab');
  await evidence.action('来源继续站内预览', card.getByRole('button', { name: 'Core.md', exact: true }), el => el.click());
  await page.locator('.cwu-document-content').getByText('合成验收记忆：回复使用中文，文件在站内预览。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '关闭文件预览', exact: true }).click();
  await page.locator('.cwu-document-backdrop').waitFor({ state: 'detached' });
  await card.getByRole('tab', { name: /^执行记录/ }).click();
  await page.waitForFunction(() => document.querySelector('.cwu-progressive-list')?.dataset.overflow === 'true');
  const completed = await card.evaluate(el => {
    const content = el.querySelector('.cwu-progressive-list > .cwu-scroll-content');
    return { running: el.classList.contains('is-running'), height: content.clientHeight, scrollHeight: content.scrollHeight, limit: Math.min(400, innerHeight * .48), overflow: getComputedStyle(content).overflowY };
  });
  assert.equal(completed.running, false); assert.ok(completed.height <= completed.limit + 1); assert.ok(completed.scrollHeight > completed.height + 200); assert.equal(completed.overflow, 'auto');
  await evidence.checkpoint('完成后记录限高并内部滚动，切换没有第二层总开关');
  const scroll = card.locator('.cwu-progressive-list > .cwu-scroll-content');
  await scroll.evaluate(el => { el.scrollTop = el.scrollHeight; });
  const command = card.locator('button.cwu-process-summary').filter({ hasText: 'node inspect.js' });
  await command.click();
  assert.ok((await scroll.evaluate(el => el.clientHeight)) <= completed.limit + 1);
  await card.getByRole('tab', { name: /^参考记忆/ }).click();
  const nameHeight = await card.getByRole('button', { name: 'Core.md', exact: true }).locator('span').first().evaluate(el => el.getBoundingClientRect().height);
  assert.ok(nameHeight < 25, 'short file name stays one line');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await card.getByRole('tab', { name: /^执行记录/ }).click();
  assert.equal(await command.getAttribute('aria-expanded'), 'true');
  await card.getByRole('button', { name: '收起本轮详情', exact: true }).click();
  assert.equal(await card.locator('[role=tabpanel]').count(), 0);
  await card.getByRole('button', { name: '展开本轮详情', exact: true }).click();
  assert.equal(await command.getAttribute('aria-expanded'), 'true');
  await evidence.checkpoint('切换和全卡片收起保留命令状态，短文件名一行，长文件名自然换行');
  await card.getByRole('button', { name: '收起本轮详情', exact: true }).click();
  await page.reload();
  await card.waitFor();
  assert.equal(await card.getAttribute('data-open'), 'false', 'refresh does not force a closed card open');
  const header = await card.locator('.cwu-turn-detail-header').evaluate(el => ({ height: el.clientHeight, children: [...el.children].map(x => x.getBoundingClientRect().top) }));
  assert.ok(header.height <= 50, 'collapsed header stays one row');
  assert.ok(Math.abs(header.children[0] - header.children[1]) < 12);
  const before = processReads.length;
  await card.getByRole('tab', { name: /^参考记忆/ }).click();
  await card.getByRole('button', { name: 'Core.md', exact: true }).waitFor();
  assert.equal(processReads.length, before, 'memory tab never reads execution records');
  await card.getByRole('tab', { name: /^执行记录/ }).click();
  await command.waitFor();
  await evidence.checkpoint('刷新保持收起，记忆不触发执行读取');
  await card.getByRole('tab', { name: /^执行记录/ }).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await card.getByRole('tab', { name: /^参考记忆/ }).getAttribute('aria-selected'), 'true');
  await page.keyboard.press('Home');
  assert.equal(await card.getByRole('tab', { name: /^执行记录/ }).getAttribute('aria-selected'), 'true');
  assert.deepEqual(errors, []);
  await evidence.checkpoint('成功后复用执行缓存，方向键和Home支持Tab切换');
}
